var INICIO_CONTRATO = '368';
var ANALISE_CONTRATO = '369';
var CORRECAO_SOLICITACAO_COMPRAS = '371';
var VALIDACAO_DOCUMENTO = '372';
var CORRECAO_DOCUMENTO_CONTRATOS = '374';
var CORRECAO_DOCUMENTO_COMPRAS = '376';
var CORRECAO_DOCUMENTO_SOLICITANTE = '377';

var REVISAO_CLAUSULAS = '372';

var APROVA_SOLICITANTE = '383';
var SOLUCAO_INCONSISTENCIA = '384';
var ALCADA_APROVACAO = '386';
var ASSINATURA_INTERNA_E_FORN = '393';
var ASSINATURA_INTERNA = '393';
