var INICIO = "5";
var ANALISE_COMPRADOR_COTACAO = "6";
var ALCADA_APROVACAO_CARTA = "20";
var CORRECAO_SOLICITANTE = "13";
var ALCADA_APROVACAO = "7";
var EXECAO_INTEGRACAO = "16";
var VALIDAR_PEDIDO_COMPRA = "19"
var ACOMPANHAMENTO_ENTREGA = "25";
var FORMULARIO_CONTRATO = "26";
var APROVACAO_SOLICITANTE = "14";
var SOLUCAO_INCONSISTENCIA = "10";
var ANALISE_TI = "376";
var GOVERNANCA_SLA = "355";
var ALCADA_APROVACAO_PA = "96";
var EXECAO_ANEXO_INTEGRACAO = "111";
var ENVIO_EMAIL_FORNECEDOR = "116";
var REAVALIAR_PA = "132";
var FINALIZADA = "11";
var ANALISE_RH = "254";
var ANALISE_OBRAS = "282";
var APROVACAO_TECNICA = "295";
var TRATATIVA_ERRO_START_ACOMP = "310";
var ANALISAR_VINCULACAO_PROD_FORNEC = "335";
var VALIDAR_CURSOS = "367";

function global() {}
