var INICIO = "5";
var ANALISE_COMPRADOR_COTACAO = "6";
var ALCADA_APROVACAO_CARTA = "20";
var CORRECAO_SOLICITANTE = "13";
var ALCADA_APROVACAO = "7";
var EXECAO_INTEGRACAO = "16";
var VALIDAR_PEDIDO_COMPRA = "19"
var ACOMPANHAMENTO_ENTREGA = "25";
var FORMULARIO_CONTRATO = "26";
var APROVACAO_SOLICITANTE = "14";
var SOLUCAO_INCONSISTENCIA = "10";
var ANALISE_TI = "62";
var GOVERNANCA_SLA = "355";
var ALCADA_APROVACAO_PA = "96";
var EXECAO_ANEXO_INTEGRACAO = "111";
var ENVIO_EMAIL_FORNECEDOR = "116";
var REAVALIAR_PA = "132";
var FINALIZADA = "11";
var ANALISE_RH = "254";
var ANALISE_OBRAS = "282";
var APROVACAO_TECNICA = "295";
var TRATATIVA_ERRO_START_ACOMP = "310";
var ANALISAR_VINCULACAO_PROD_FORNEC = "335";

//inicio atividades de contrato

var INICIO_CONTRATO = '368';
var ANALISE_CONTRATO = '369';
var CORRECAO_SOLICITACAO_COMPRAS = '371';
var VALIDACAO_DOCUMENTO = '372';
var CORRECAO_DOCUMENTO_CONTRATOS = '374';
var CORRECAO_DOCUMENTO_COMPRAS = '376';
var CORRECAO_DOCUMENTO_SOLICITANTE = '377';

var REVISAO_CLAUSULAS = '493';

var INCONSISTENCIA_DADOS_PROTHEUS = "382";
var APROVA_SOLICITANTE = '383';
var SOLUCAO_INCONSISTENCIA = '384';
var ALCADA_APROVACAO_CONTRATO = '386';
var CANCELAR_SOLICITACAO = "391";
var ASSINATURA_INTERNA_E_FORN = '393';
var VALIDACAO_ASSINATURA_FORNECEDOR = '493';
var ASSINATURA_INTERNA = '493';
var CHANCELAMENTO_CONTRATO = "372";



//fim atividades de contrato

//inicio atividades de acompanhamento de entrega


var informarentrega = '468';
var verificaratraso = '464';

//fim atividades de acompanhamento de entrega

function global() {}